-- Create BRANDS table
CREATE TABLE BRANDS (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE
);

-- Insert initial brand (ZARA)
INSERT INTO BRANDS (ID, NAME) VALUES (1, 'ZARA');

-- Create PRICES table with foreign key to BRANDS
CREATE TABLE PRICES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CURR VARCHAR(3) NOT NULL,
    CONSTRAINT FK_PRICES_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID)
);

-- Create index for query performance
CREATE INDEX IDX_PRICES_QUERY ON PRICES(BRAND_ID, PRODUCT_ID, START_DATE, END_DATE);

